name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21  # Cambiado aquí para claridad
      uses: actions/setup-java@v4
      with:
        java-version: '21' # <--- ESTE ES EL CAMBIO CLAVE
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn -B package
      working-directory: vib_ED_pt2

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
          name: vib_ED_tests-jar
          path: vib_ED_pt2/target/*.jar
